### ISSUE TITLE
Wrong message when I search for gift cards

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusGiftCardPlugin#1]
When I search for a gift card on this page: `http://127.0.0.1:8000/app_dev.php/en_US/gift-card/search` for a gift card that doesn't exist I get this message: `Your gift card will only be charged if you complete your order`. The message should probably be `The gift card does not exist`.

If I search for a gift card with balance $0 I get the same message. I should instead see a balance of $0.

**Comment by bitbager** [comment]
Should be fixed by #11

**Comment by igormukhingmailcom** [comment]
As far as #11 is merged - closing issue.
