### ISSUE TITLE
Add giftCard from purchase process 

### ISSUE THREAD

**Issue by sahnhi** [Setono/SyliusGiftCardPlugin#112]
Hello,

We use your plugin for our application.
But I have a problem with the payment of a gift card from a Shop front API.

How is the purchase process for a gift card, if we want to buy it ?
How can I associate a gift card with a payment?

Hope to have an answer,
Thank you

**Comment by loevgaard** [comment]
To buy a gift card you create a product and set the `Gift card` to true, then it's just like any other product that you can buy

**Comment by sahnhi** [comment]
Thank you @loevgaard , I will try to do this
