### ISSUE TITLE
Installation conflict symfony/security

### ISSUE THREAD

**Issue by JulienLoison** [Setono/SyliusGiftCardPlugin#157]
Hello,

When installing the plugin on Sylius 1.10.2 / Symfony 5.3.7, I have some dependencies issues : 

```
Problem 1
    - setono/sylius-gift-card-plugin[v0.11.5, ..., 0.11.x-dev] require symfony/security ^4.4 || ^5.0 -> satisfiable by symfony/security[v4.4.0-BETA1, ..., 4.4.x-dev].
    - symfony/security[v4.4.0-BETA1, ..., 4.4.x-dev] require symfony/http-kernel ^4.4 -> found symfony/http-kernel[v4.4.0-BETA1, ..., 4.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires setono/sylius-gift-card-plugin ^0.11.5 -> satisfiable by setono/sylius-gift-card-plugin[v0.11.5, 0.11.x-dev].
```

This also happens when I try to force the version to the 0.12.x-dev

```
Problem 1
    - symfony/security[v4.4.0-BETA1, ..., 4.4.x-dev] require symfony/http-kernel ^4.4 -> found symfony/http-kernel[v4.4.0-BETA1, ..., 4.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - setono/sylius-gift-card-plugin 0.12.x-dev requires symfony/security ^4.4 || ^5.0 -> satisfiable by symfony/security[v4.4.0-BETA1, ..., 4.4.x-dev].
    - Root composer.json requires setono/sylius-gift-card-plugin ^0.12 -> satisfiable by setono/sylius-gift-card-plugin[0.12.x-dev].`
```

My project's composer.lock file has those dependencies : 
- symfony/security-bundle v5.3.4
- symfony/http-kernel v5.4.6

[Sylius's composer.json](https://github.com/Sylius/Sylius/blob/master/composer.json) also shows a requirement to symfony/security-bundle (not symfony/security)

Finally, the [symfony/security package](https://packagist.org/packages/symfony/security) has no 5.+ releases but the [symfony/security-bundle package](https://packagist.org/packages/symfony/security-bundle) do

Shouldn't the symfony/security dependency be replaced by the symfony/security-bundle dependency ?

**Comment by loevgaard** [comment]
In fact @Roshyo just fixed this for `0.12.x` (https://github.com/Setono/SyliusGiftCardPlugin/pull/156). It should have been in `0.11.x`. He is on that now. Thanks :)

**Comment by loevgaard** [comment]
Hi, @JulienLoison. Can you come up with a working PR for 0.11? It seems the PR @Roshyo made doesn't build atm

**Comment by loevgaard** [comment]
... and right now we don't have the time to look into it :)

**Comment by JulienLoison** [comment]
With 0.11 beeing restricted to Sylius 1.7, there is no obligation to change the dependency : Sylius 1.7 is Symfony 4 only, so the symfony/security 4.x should suffice ?

**Comment by Roshyo** [comment]
0.11 is not restricted to Sylius 1.7. And in fact, it works under 1.10, but with Symfony 4, not 5.

Then perhaps the way would simply be to restrict Symfony deps to 4.x for 0.11. But we need to finish the work on 0.12 ASAP then :D

**Comment by loevgaard** [comment]
Maybe we could remove the `symfony/security` from `require` and move it to `require-dev` and make a note about it in the README
