### ISSUE TITLE
A new entity was found through the relationship 'Setono\SyliusGiftCardPlugin\Model\GiftCard#orderItemUnit'

### ISSUE THREAD

**Issue by devphp06** [Setono/SyliusGiftCardPlugin#159]
Hi,

I am using version 0.8.7 of this plugin over Sylius v1.6.

I have successfully integrated the plugin and admin can see/create gift cards and also add/edit products to enable/disable them as a gift card.

I create a product and make it a gift card. Now when I login as a customer and try to purchase that gift card product, I face this exception at the final payment step when I click Place Order and Pay.

app.CRITICAL: A new entity was found through the relationship 'Setono\SyliusGiftCardPlugin\Model\GiftCard#orderItemUnit' that was not configured to cascade persist operations for entity: Sylius\Component\Core\Model\OrderItemUnit@000000006aa1ed9f0000000017521ee5. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Sylius\Component\Core\Model\OrderItemUnit#__toString()' to get a clue.

app.CRITICAL: #0 /var/www/html/sylius_marketplace/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3461): Doctrine\ORM\ORMInvalidArgumentException::newEntitiesFoundThroughRelationships(Array) #1 /var/www/html/sylius_marketplace/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(366)

I do not have much knowledge of Sylius but I am pretty familiar with Symfony.

Any help would be appreciated.

Thanks

**Comment by loevgaard** [comment]
Hi, can you upgrade to the newest version of this plugin? Thank you :)

If the problem persists after that, please open a new issue.

**Comment by devphp06** [comment]
Hi, thank you for the quick feedback.

It will be a hectic job to upgrade due to dependencies over other plugins. The project is using too many plugins. Can you confirm if this can be due to the old version of this plugin so I put time and efforts to upgrade the plugins.

Thanks.

**Comment by loevgaard** [comment]
Hi, there. I don't know, but since we haven't had any similar issue I presume that's a confirmation of some sort :)

**Comment by devphp06** [comment]
Okay, thank you. I will try to upgrade the plugin and see if the issue persists.

**Comment by loevgaard** [comment]
You're welcome. Hope you'll make it work :)

Please notice that we're upgrading the plugin to use the new API platform for version 0.12 of this plugin. So if you're on the newest Sylius, maybe consider that branch instead :)
