### ISSUE TITLE
Add origin property to gift card to tell where gift card was created

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusGiftCardPlugin#166]
A simple string property on the gift card to tell where the gift card was created, i.e. during checkout, from an external application, through an external partner, through an RMA process etc.

**Comment by Roshyo** [comment]
I fear that `origin` may be confusing, and I would like us to think about a clearer term. Here are my ideas:

* Created for
* Created during
* Creation reason

What do you think ?

**Comment by loevgaard** [comment]
I ❤️ the word `origin`, but I see your point :D

**Comment by loevgaard** [comment]
Here's the definition of 'origin': `the point or place where something begins, arises, or is derived` so in my mind it's still the best word :D
