### ISSUE TITLE
Adding ValidFrom and ValidUntil dates

### ISSUE THREAD

**Issue by Roshyo** [Setono/SyliusGiftCardPlugin#169]
We should be able to define when a Gift Card is expiring. Let's say that some of them should be valid for 2 years, and some others for 6 months, depending on the needs. So a Gift Card should have a validFrom and a validUntil dates

**Comment by loevgaard** [comment]
For this issue I think we should have a configuration option; `default_validity_period` - probably given in days or hours.

I am not sure we need the 'validFrom' though. What's the use case for that?
