### ISSUE TITLE
Not compatible with sylius 1.10

### ISSUE THREAD

**Issue by seizan8** [Setono/SyliusGiftCardPlugin#179]
GiftCardPlugin require friendsofsymfony/rest-bundle ^2.8

sylius/resource-bundle requires friendsofsymfony/rest-bundle ^3.0

Same issue as for sylius 1.8 and 1.9 #160

**Comment by loevgaard** [comment]
Can you check if this has been fixed by now? Please reopen this issue if it hasn't :)

**Comment by seizan8** [comment]
It works for the most part.
I could easily install it, configure it and create a new gift card in my backend.
However, it fails in the frontend when I open my cart summary: #197

**Comment by loevgaard** [comment]
Thank you for testing it out so fast. I will look into this on Friday :)
