### ISSUE TITLE
0.11.7 Incompatible with friendsofsymfony/rest-bundle ^3.0

### ISSUE THREAD

**Issue by seizan8** [Setono/SyliusGiftCardPlugin#197]
Using the 0.11.7 version of SyliusGiftCardPlugin.

It requires friendsofsymfony/rest-bundle: "^2.8 || ^3.0".

However FOS\RestBundle\View\View does not have a setTemplate method anymore since 3.0
When I open my cart summary in the frontend, I get this:
**Attempted to call an undefined method named "setTemplate" of class "FOS\RestBundle\View\View".
in vendor/setono/sylius-gift-card-plugin/src/Controller/Action/AddGiftCardToOrderAction.php (line 80)**

Requiring "^2.8" does not work as 2.8 does not support PHP 8.

I don't have much experience with the REST bundle. Why is it needed?
Couldn't the Action simply extend symfony's AbstractController and use $this->render($template, $context); like every normal Action?

**Comment by loevgaard** [comment]
Hi @seizan8 

Wdyt about this PR: https://github.com/Setono/SyliusGiftCardPlugin/pull/199? :) I reckon it should fix this whole compatibility problem

**Comment by loevgaard** [comment]
I have merged it into `0.11`. Could you try and test it out before we release `0.11.8`?

**Comment by seizan8** [comment]
@loevgaard yeah sure. How do I do this though? Like, It seems I am not able to require that specific branch.

**Comment by loevgaard** [comment]
Instead of `^0.11` you will replace that with `0.11.x-dev` in your `composer.json` and then run `composer update setono/sylius-gift-card-plugin`. I suppose `0.11.x@dev` would also work

**Comment by seizan8** [comment]
Oh alright. I forgot the "-dev", thx. 

I did not get an error this time! However, the button does not work. I'll look more into it tomorrow as something came up. 
I assume it's an error on my end, not having the Plugin integrated correctly most likely.

**Comment by loevgaard** [comment]
Sounds great, @seizan8 :)

**Comment by seizan8** [comment]
Aaaaalright. I got it working. I had some issue with the sylius bootstrap theme. 

This looks good! The issue I had has been resolved. Thanks a lot :)

**Comment by loevgaard** [comment]
Will make a release now then. Thank you for testing :)
