### ISSUE TITLE
Small layout error when editing gift card configurations

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusGiftCardPlugin#207]
![image](https://user-images.githubusercontent.com/2412177/166231778-9180fc3a-d272-493e-9aa5-86d9db1916f6.png)

**Comment by Roshyo** [comment]
I am not sure exactly what we can do to keep things clean since it is a Semantic UI problem. You have the same on product media for example
![image](https://user-images.githubusercontent.com/9363039/167070787-e3457478-d9dc-4e00-b140-629b9491da70.png)
