### ISSUE TITLE
Add preferred choices to list of paper formats

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusGiftCardPlugin#209]
![image](https://user-images.githubusercontent.com/2412177/166232252-f24b4653-ded8-4a01-9e3d-682658791f15.png)

**Comment by Roshyo** [comment]
And what would be the list of those preferred choices ? Isn't that too subjective ?
Or should we make it configurable ?

**Comment by loevgaard** [comment]
It is subjective, but I don't want to make it configurable by now. Imo just A4, A5 and A6 for now. My guess is that will cover 99% as of right now :D
