### ISSUE TITLE
GiftCardType: customer field doesnt use token for label

### ISSUE THREAD

**Issue by seizan8** [Setono/SyliusGiftCardPlugin#215]
`Setono\SyliusGiftCardPlugin\Form\Type\GiftCardType`

The customer field doesn't have a label parameter and so simply uses "customer" instead of a translation token.
"sylius.ui.customer" should probably used as label here, similar to the amount field.

![grafik](https://user-images.githubusercontent.com/32196755/166950613-4ee5b233-a502-4268-b751-3186caf207cf.png)

**Comment by Roshyo** [comment]
Thanks for reporting this issue @seizan8 ! it is now fixed on 0.12 branch.

**Comment by seizan8** [comment]
neat. thanks :)
