### ISSUE TITLE
How do you purchase/add to cart a gift card in the API?

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusGiftCardPlugin#232]
Can we document or figure out if this is possible (with the configurable amount, message etc)

**Comment by Roshyo** [comment]
It is possible with the regular endpoint to add item to cart
![image](https://user-images.githubusercontent.com/9363039/171566955-7ec97612-c8a0-4606-9311-4249777f4677.png)

With this field `amount` you can define the GC amount you want. It is simply ignored if the product is not a GC. You can also add the custom message there.

I will add some documentation though.

**Comment by loevgaard** [comment]
Thank you, @Roshyo 🎉
