### ISSUE TITLE
Installation is not possible. Folders missing.

### ISSUE THREAD

**Issue by jakubiak** [Setono/SyliusGiftCardPlugin#24]
I can't install plugin from readme file because:
`cp -r vendor/setono/sylius-gift-card-plugin/tests/Application/templates/bundles/SyliusShopBundle/ templates/bundles/SyliusShopBundle/
cp: can't stat 'vendor/setono/sylius-gift-card-plugin/tests/Application/templates/bundles/SyliusShopBundle': No such file or directory`

![image](https://user-images.githubusercontent.com/2519012/67381052-9163b200-f58b-11e9-9826-435024db3f21.png)

Some folders are excluded in .gitattributes

Please fix this

**Comment by loevgaard** [comment]
Meanwhile you can get the files here: https://github.com/Setono/SyliusGiftCardPlugin/tree/master/tests/Application/templates/bundles
