### ISSUE TITLE
Remove code from adjustment label

### ISSUE THREAD

**Issue by igormukhingmailcom** [Setono/SyliusGiftCardPlugin#40]
- To beautify at least this view: https://www.dropbox.com/s/7z3y9iu7a25jrd1/Screenshot%202019-12-06%2014.28.58.png?dl=0
- So gift cards can be aggregated by label at `AdjustmentsByLabelAggregator`

Code still can be retrieved at `$adjustment->getOriginCode()`

**Comment by loevgaard** [comment]
Good idea
