### ISSUE TITLE
Unrecognized field: default

### ISSUE THREAD

**Issue by senghe** [Setono/SyliusGiftCardPlugin#60]
Hey. I've just installed your plugin (version 0.8.1) on Sylius 1.6 and have an issue with printing giftcard to PDF.

Steps:

1. Install fixtures
2. Create simple giftcard
3. Try to print giftcard into pdf

Result:
![image](https://user-images.githubusercontent.com/2512726/76764483-324e4600-6795-11ea-91ea-2aca5ac4df44.png)

**Comment by loevgaard** [comment]
Hi @senghe 

Thank you for using the plugin. This issue should have been fixed in the newest release, `0.8.2`. Can you confirm this?
