### ISSUE TITLE
Order fixtures issue

### ISSUE THREAD

**Issue by senghe** [Setono/SyliusGiftCardPlugin#61]
Hello! :) 

I'm using your plugin (0.8.1) on Sylius 1.6.

As you recommend, I'm using your order trait:

```php
class Order extends BaseOrder implements SetonoSyliusGiftCardPluginOrderInterface
{
    use SetonoSyliusGiftCardPluginOrderTrait {
        SetonoSyliusGiftCardPluginOrderTrait::__construct as private __giftCardTraitConstruct;
    }
}
```

When I do this, my fixtures installation command tells me:

![image](https://user-images.githubusercontent.com/2512726/76764892-e0f28680-6795-11ea-94bf-b0efca5a649a.png)

But when I do it this way:

```php
class Order extends BaseOrder implements SetonoSyliusGiftCardPluginOrderInterface
{
    use SetonoSyliusGiftCardPluginOrderTrait;

    public function __construct()
    {
        parent::__construct();
        $this->giftCards = new ArrayCollection();
    }
}
```

It works correctly.

**Comment by loevgaard** [comment]
Oh, we haven't updated the readme. See this file: https://github.com/Setono/SyliusGiftCardPlugin/blob/master/tests/Application/Model/Order.php. This is the correct way to do it :)
