### ISSUE TITLE
Uncaught Exception: Unable to find template ""

### ISSUE THREAD

**Issue by TheDevilOnLine** [Setono/SyliusGiftCardPlugin#63]
Following the default installation instructions on a clear Sylius 1.7 installation leads to a 'Uncaught Exception: Unable to find template ""' error.

**Comment by loevgaard** [comment]
Hi @TheDevilOnLine 

Thanks for reporting!

What does your log say? I just ran into this issue myself on another plugin and higher up in the log the reason for the exception was found

**Comment by TheDevilOnLine** [comment]
Uncaught Error: Call to a member function filter() on null {"exception":"[object] (Error(code: 0): Call to a member function filter() on null at D:\\github\\sylius-saas\\vendor\\sylius\\sylius\\src\\Sylius\\Component\\Order\\Model\\Order.php:288

Figured it's the same issue as #61
