### ISSUE TITLE
how does coupon activation work?

### ISSUE THREAD

**Issue by ThomasViennet** [Setono/SyliusGiftCardPlugin#67]
Hello,

Thank you for this plug-in!
I have a question about how it works.

I created a product and turned it into a gift card. 
![Capture d’écran 2020-04-23 à 17 52 22](https://user-images.githubusercontent.com/18012092/80120840-dd6bcf80-858b-11ea-87e1-bc562b7e4ee6.png)

It works for the purchase and I find my new coupon. 
![Capture d’écran 2020-04-23 à 17 53 48](https://user-images.githubusercontent.com/18012092/80120852-e2308380-858b-11ea-9264-85e10c811f8c.png)

But I don't understand why sometimes he's Enabled other times Disabled.

Can you tell me the logic behind this process please?

Thank you very much for your help!

**Comment by loevgaard** [comment]
I am glad you find it useful. Please report any bugs, misconceptions, or things you think could be made better :)

The gift card is enabled when the order is paid (https://github.com/Setono/SyliusGiftCardPlugin/blob/master/src/Resources/config/state_machine/sylius_order_payment.yaml).

**Comment by ThomasViennet** [comment]
Ok thank you for your help.
