### ISSUE TITLE
Allow to change the redirect URL when adding or deleting gift cards

### ISSUE THREAD

**Issue by JulienLoison** [Setono/SyliusGiftCardPlugin#69]
I had to allow the customer to add and remove gift card on the payment step of the checkout process. I needed the customer to be redirected to the payment step and not to the cart summary page. 
I had to override `AddGiftCardToOrderAction`, `RemoveGiftCardFromOrderAction` and `addGiftCardToOrder.html.twig` to achieve that (replacing `sylius_shop_cart_summary` by the route I wanted to redirect to)

May be it could be done with the referrer from the request, this way no matter where your user decides to implement the plugin, the customer will be redirected to the page the request came from ?

**Comment by loevgaard** [comment]
Hi @JulienLoison 

That's a very good idea. Can you come up with a PR for that? :)
