### ISSUE TITLE
Think about renaming `findByEmailPart`

### ISSUE THREAD

**Issue by igormukhingmailcom** [Setono/SyliusGiftCardPlugin#77]
As `AdminOrderCreation` plugin have the same name at its `CustomerRepositoryTrait`.

Something like `findByEmailPartForGiftCard` (append context) or `setonoFindByEmailPart` (prepend vendor name).

Reasons:
- Interfaces the same right now, but implementations still a bit different
- Something can change at future

Related:
- https://github.com/Setono/SyliusGiftCardPlugin/pull/54
- https://github.com/Setono/SyliusGiftCardPlugin/pull/76

**Comment by chadyred** [comment]
+1 it could be great
