### ISSUE TITLE
JS file never included - Invalid gift card renders JSON

### ISSUE THREAD

**Issue by bonswouar** [Setono/SyliusGiftCardPlugin#79]
Obviously a JS problem, same as #44, so I checked which JS files are loaded... And the only one, `setono-sylius-gift-card-add-gift-card-to-order.js`, isn't.
I checked in the vendor files, and apparently it's never included anywhere ! And surprisingly I didn't find any issue here about this.
I also tried to manually include it, but that doesn't seem to fix the problem.
I even tried to copy this block from [test cart summary file](https://github.com/Setono/SyliusGiftCardPlugin/blob/f28906ab0dda65f7d6d9d8edfaa0306fadaddc3f/tests/Application/templates/bundles/SyliusShopBundle/Cart/summary.html.twig) (only file I found using this js here)  :
```html
    <script src="{{ asset('bundles/setonosyliusgiftcardplugin/setono-sylius-gift-card-add-gift-card-to-order.js') }}"></script>
    <script>
        $('#setono-sylius-gift-card-add-gift-card-to-order').addGiftCardToOrder();
    </script>
```
But again, that didn't fix the problem.

**Comment by igormukhingmailcom** [comment]
Hi, @bonswouar 
- Have you executed `php bin/console assets:install` after plugin installation (https://github.com/Setono/SyliusGiftCardPlugin#install-assets)?
- Have you copied templates (https://github.com/Setono/SyliusGiftCardPlugin#copy-templates) to have js included like at example template https://github.com/Setono/SyliusGiftCardPlugin/blob/master/tests/Application/templates/bundles/SyliusShopBundle/Cart/summary.html.twig#L22?

**Comment by bonswouar** [comment]
Okay I didn't notice it was normal that the template to copy was in `test` directory, that's not very intuitive. Should have fully read the readme though ;)
But as I said, I did copy the `javascript` block from this template. It then does correctly load the JS file (yes my assets are installed), but it doesn't affect the problem.

**Comment by bonswouar** [comment]
Anyway I just noticed the project is using an old version of this bundle, nevermind
