### ISSUE TITLE
unable to install >> don't install thecodingmachine/safe v0.1.16

### ISSUE THREAD

**Issue by starmate** [Setono/SyliusGiftCardPlugin#93]
Hello,

When trying to install (composer require setono/sylius-gift-card-plugin), I have the following issue:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for setono/sylius-gift-card-plugin ^0.7.0 -> satisfiable by setono/sylius-gift-card-plugin[v0.7.0].
    - Conclusion: remove thecodingmachine/safe v0.1.16
    - Conclusion: don't install thecodingmachine/safe v0.1.16
    - setono/sylius-gift-card-plugin v0.7.0 requires thecodingmachine/safe ^1.0 -> satisfiable by thecodingmachine/safe[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.1, v1.1.1, v1.1.2, v1.1.3].
    - Can only install one of: thecodingmachine/safe[v1.0.0, v0.1.16].
    - Can only install one of: thecodingmachine/safe[v1.0.1, v0.1.16].
    - Can only install one of: thecodingmachine/safe[v1.0.2, v0.1.16].
    - Can only install one of: thecodingmachine/safe[v1.0.3, v0.1.16].
    - Can only install one of: thecodingmachine/safe[v1.1, v0.1.16].
    - Can only install one of: thecodingmachine/safe[v1.1.1, v0.1.16].
    - Can only install one of: thecodingmachine/safe[v1.1.2, v0.1.16].
    - Can only install one of: thecodingmachine/safe[v1.1.3, v0.1.16].
    - Installation request for thecodingmachine/safe (locked at v0.1.16) -> satisfiable by thecodingmachine/safe[v0.1.16].

Installation failed, reverting ./composer.json to its original content.

Could you please help me? I'd love to try this extension but I am stuck at installation stage for now.

Thanks,

Jon

**Comment by loevgaard** [comment]
Could you try and upgrade your `thecodingmachine/safe` to `^1.0` first?

**Comment by starmate** [comment]
@loevgaard thanks for your reply.
I acutally tried and I get the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symplify/easy-coding-standard v4.8.0 requires thecodingmachine/safe ^0.1.3 -> satisfiable by thecodingmachine/safe[0.1.x-dev, v0.1.10, v0.1.11, v0.1.12, v0.1.13, v0.1.14, v0.1.15, v0.1.16, v0.1.3, v0.1.4, v0.1.5, v0.1.6, v0.1.7, v0.1.8, v0.1.9] but these conflict with your requirements or minimum-stability.
    - symplify/easy-coding-standard v4.8.0 requires thecodingmachine/safe ^0.1.3 -> satisfiable by thecodingmachine/safe[0.1.x-dev, v0.1.10, v0.1.11, v0.1.12, v0.1.13, v0.1.14, v0.1.15, v0.1.16, v0.1.3, v0.1.4, v0.1.5, v0.1.6, v0.1.7, v0.1.8, v0.1.9] but these conflict with your requirements or minimum-stability.
    - symplify/easy-coding-standard v4.8.0 requires thecodingmachine/safe ^0.1.3 -> satisfiable by thecodingmachine/safe[0.1.x-dev, v0.1.10, v0.1.11, v0.1.12, v0.1.13, v0.1.14, v0.1.15, v0.1.16, v0.1.3, v0.1.4, v0.1.5, v0.1.6, v0.1.7, v0.1.8, v0.1.9] but these conflict with your requirements or minimum-stability.
    - Installation request for symplify/easy-coding-standard (locked at v4.8.0) -> satisfiable by symplify/easy-coding-standard[v4.8.0].

**Comment by loevgaard** [comment]
You are using a way too old version of the easy coding standard. You should upgrade your packages. Then everything will be installable in the end :)

**Comment by starmate** [comment]
@loevgaard thanks again for your reply.

I am using last version of Sylius and I am quite a newbie. 

Do I still need to upgrade and if yes, how? I've tried to use the following : composer symplify/easy-coding-standard --dev but it doesn't help much. I am not sure to follow the right path. What would you advise?

**Comment by loevgaard** [comment]
Hi starmate. The best thing you can do is to join the Symfony and Sylius community on Slack and ask your question there. It's a bit back and forth with updating deps :)

**Comment by starmate** [comment]
Hi @loevgaard ,

Issue fixed. Composer was linked to php 7.1.x. Therfore, old version of sylius was installed.
Thanks again for your help and for your module! I really appreciate it.

**Comment by loevgaard** [comment]
Great, @starmate :)
