### ISSUE TITLE
Make PDF look better

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusGiftCardPlugin#95]
Right now a generated PDF looks like this:

![image](https://user-images.githubusercontent.com/2412177/91553050-1a2a4780-e92d-11ea-8019-052ca83ebcbe.png)

Suggestions:
- [ ] Add texts like: Amount: $123 and Code: XXXX
- [ ] Make it fit on the top half of an A4, so it can be cut and fit in an envelope

**Comment by sahnhi** [comment]
Hello, 

I've tried to override the pdf.html.twig to customize it with our branding.
But the PDF doesn't seems to take the "img" from a cloudinary url.
And how can I  put in landscape format ?

Thanks,

**Comment by loevgaard** [comment]
This is fixed in `0.12` branch
